#!/usr/bin/env python3
"""
gen_dark_hardcoded.py - generates assets/css/dark-hardcoded.css

* Every rule is scoped to html.dark, so light mode is unaffected.
* Module PHP files are READ ONLY. This script never edits them.
* Selectors match exact declarations (";" or end of attribute), so #fff does
  not also match #fffbf5.

Covers: hardcoded light values in inline style="" attributes that appear in
tools/dark_palette.py.

Not covered (written to tools/dark_hardcoded_review.csv):
  * <style> blocks inside page files
  * gradients
  * values not in the palette tables

Usage (from project root):
  python tools\\gen_dark_hardcoded.py
"""
import csv
import os
import re
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import dark_palette as dp

ROOT = dp.ROOT
OUT_CSS = os.path.join(ROOT, 'assets', 'css', 'dark-hardcoded.css')
OUT_REVIEW = os.path.join(ROOT, 'tools', 'dark_hardcoded_review.csv')


def table_and_outprop(prop):
    p = prop.lower()
    if p.startswith('background'):
        return dp.BG_MAP, 'background-color'
    if p == 'color':
        return dp.TEXT_MAP, 'color'
    if p.startswith('border'):
        # Never emit a border shorthand: a color-only shorthand resets width and style.
        if p == 'border':
            return dp.BORDER_MAP, 'border-color'
        if p.endswith('-color'):
            return dp.BORDER_MAP, p
        return dp.BORDER_MAP, p + '-color'
    return None, None


def selectors_for(prop, token):
    """Exact-match selectors for `prop:token` with and without a space after the colon."""
    out = []
    for sep in (':', ': '):
        needle = f'{prop}{sep}{token}'
        out.append(f'html.dark [style*="{needle};" i]')
        out.append(f'html.dark [style$="{needle}" i]')
    return out


def collect():
    # decl -> set of selectors
    groups = defaultdict(set)
    review = []
    for dirpath, _, files in os.walk(os.path.join(ROOT, 'modules')):
        for name in files:
            if not name.lower().endswith(('.php', '.html')):
                continue
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, ROOT)
            if dp.should_skip(rel):
                continue
            with open(full, 'r', encoding='utf-8', errors='replace') as fh:
                text = fh.read()
            if re.search(r'<style\b', text, re.I):
                review.append({'file': rel, 'item': '<style> block', 'value': '', 'note': 'manual review'})
            for m in dp.STYLE_ATTR_RE.finditer(text):
                for dm in dp.DECL_RE.finditer(m.group(3)):
                    prop, val = dm.group(1).lower(), dm.group(2).strip()
                    if 'gradient' in val.lower():
                        review.append({'file': rel, 'item': prop, 'value': val, 'note': 'gradient skipped'})
                        continue
                    table, out_prop = table_and_outprop(prop)
                    if table is None:
                        continue
                    for hm in dp.HEX_RE.finditer(val):
                        tok = hm.group(0).lower()
                        if tok not in table:
                            continue
                        decl = f'{out_prop}: {table[tok]} !important'
                        groups[decl].update(selectors_for(prop, tok))
                        if table is dp.BORDER_MAP:
                            # e.g. "border:1px solid #e5e7eb" -> only the color changes
                            bdecl = f'border-color: {table[tok]} !important'
                            for style_kw in ('solid', 'dashed', 'dotted'):
                                groups[bdecl].add(f'html.dark [style*="{style_kw} {tok}" i]')
    return groups, review


def main():
    groups, review = collect()

    lines = [
        '/* dark-hardcoded.css - GENERATED by tools/gen_dark_hardcoded.py. Do not edit by hand.',
        ' * Every rule requires html.dark, so light mode is unaffected.',
        ' * Covers hardcoded light values in inline style="" attributes only.',
        ' */',
    ]
    total_selectors = 0
    for decl in sorted(groups):
        sels = sorted(groups[decl])
        total_selectors += len(sels)
        lines.append(',\n'.join(sels) + ' {')
        lines.append(f'    {decl};')
        lines.append('}')
        lines.append('')

    with open(OUT_CSS, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write('\n'.join(lines))

    with open(OUT_REVIEW, 'w', encoding='utf-8-sig', newline='') as fh:
        w = csv.DictWriter(fh, fieldnames=['file', 'item', 'value', 'note'])
        w.writeheader()
        w.writerows(review)

    print('GENERATED - header.php NOT changed, no module files changed')
    print(f'Declaration groups: {len(groups)}')
    print(f'Selectors: {total_selectors}')
    print(f'Written: {OUT_CSS}')
    print(f'Manual review items: {len(review)} -> {OUT_REVIEW}')


if __name__ == '__main__':
    main()
